version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    container_name: ncert
    env_file:
      - secrets/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app
      - ./nginx:/etc/nginx/user_conf.d:ro
      - letsencrypt:/etc/letsencrypt

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: aggregator
    hostname: web
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && hypercorn backend.asgi:application -m 777 --workers 1 --bind unix:/app/backend.sock"
    volumes:
      - ./src:/app

volumes:
  letsencrypt: